### ISSUE TITLE
Bug: can't handle empty output template

### ISSUE THREAD

**Issue by its-mrarsikk** [MatusGuy/youtube-dl_GUI#3]
I was trying to find bugs, and found one. When i empty the Outpput Template, it starts to say that there is more than 1 video to download, but it success download playlists other time, btw i specified only [one video](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
![image](https://user-images.githubusercontent.com/94739102/158503193-4ebbabc9-4dec-4f97-83b1-d4edfbfa55c4.png)

**Comment by MatusGuy** [comment]
You're not using output template right.
I referenced in an comment to issue #2 that I'd switch output template to something else.
Add the filename to the destination folder `path\to\video.mp4` and leave output template empty.
